# Generated by Django 3.2.16 on 2025-05-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_contact_alter_applicant_id_alter_bookmarkjob_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Vacancy',
        ),
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='job',
            name='last_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='passedout',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='job',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='job',
            name='url',
        ),
    ]
