# Generated by Django 3.2.16 on 2025-05-10 06:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        # ('taggit', '0004_auto_20250510_1208'),
        ('jobapp', '0003_auto_20250507_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Experience',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='Vacancy',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='jobapp.category'),
        ),
        migrations.AddField(
            model_name='job',
            name='company_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='gender',
            field=models.CharField(default='Male', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='last_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='passedout',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
